### ISSUE TITLE
Search bar responsive issues

### ISSUE THREAD

**Issue by Suvink** [Suvink/volunteer-me#4]
**Describe the bug**
The search bar overflows after around 500px screen width

**Screenshots**

![Screen Shot 2020-05-26 at 8 12 57 PM](https://user-images.githubusercontent.com/10671497/82914587-53999280-9f8d-11ea-9dff-bbb14e65e9bd.png)

**Noted on**
 - Device: Pixel2 XL

**Comment by AderbalFilho** [comment]
Can I do this one?
